Completed javascript-timers
amorabryan/c0523-code-solutions pull request #60
Opened 2023-06-05 21:33 UTC by amorabryan

![Interval](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/89ebc51b-7d93-476c-a413-22ba715416f2)
![Timeout](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/4889e4ed-85da-4d28-8560-05a4212837ff)

2023-06-05 21:37 UTC, amorabryan commented
![Timeout](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/cd0d57a5-a39f-4228-ad72-bc96c484384e)
![Interval](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/18b9eb63-c82a-43ec-a81c-cf6a571a4df8)

2023-06-05 21:39 UTC, shawnkost requested changes
A few changes here Bryan!

2023-06-05 21:39 UTC, shawnkost commented on javascript-timers/interval.js
> +  const $countdownDisplay = document.querySelector('.countdown-display');
This should be done globally. By including it inside the function, you're forcing us to traverse the DOM over and over every single time this function gets called

2023-06-05 21:39 UTC, shawnkost commented on javascript-timers/interval.js
> +    clearInterval(countdown);
You're passing in the wrong argument here. The argument should be an id that gets returned by the `setInterval` function

2023-06-05 21:39 UTC, shawnkost commented on javascript-timers/timeout.js
> +  const $message = document.querySelector('.message');
Move this globally rather than inside the function

2023-06-12 17:08 UTC, shawnkost approved these changes
👍🏻

2023-06-12 18:00 UTC, merged