Completed Phase 1 - react-design
amorabryan/c0523-code-solutions pull request #85
Opened 2023-06-28 18:03 UTC by amorabryan

![image](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/9d44a3ab-f324-4ebb-8212-9a61f3f007d0)

2023-06-28 18:32 UTC, TimelikeClosure requested changes
@amorabryan Phase 1 looks good, looking forward to Phase 2.

2023-06-28 21:22 UTC, TimelikeClosure requested changes
@amorabryan Phase 2 looks good, looking forward to Phase 3.

2023-06-28 23:21 UTC, amorabryan commented
![Recording 2023-06-28 at 16 20 16](https://github.com/amorabryan/c0523-code-solutions/assets/117689047/246337c2-d9ca-4911-b37f-4547e67bb931)

2023-06-29 16:16 UTC, TimelikeClosure approved these changes

2023-06-29 16:55 UTC, merged